services:
  rabbitmq:
    image: "heidiks/rabbitmq-delayed-message-exchange:latest"
    hostname: rabbitmqhost
    restart: always
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для управляющего интерфейс
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq  # сохраняем данные на диске
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmqlogin  # имя пользователя
      - RABBITMQ_DEFAULT_PASS=rabbitmqpassword  # пароль
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766  # 1.3 Gib